/* ═══════════════════════════════════════════
   FREEK BOES · PORTFOLIO — data.js
   Bilingual content (EN / NL).
   Loaded before script.js in index.html.
═══════════════════════════════════════════ */

const DATA = {
  en: {
    status:  'Final-year student · Thomas More',
    role:    'Applied Computer Science',
    tagline: 'Software developer focused on building mobile and web applications that solve real business problems.',
    nav: {
      about:      'About',
      skills:     'Skills',
      work:       'Work',
      experience: 'Experience',
      education:  'Education',
      resume:     'Resume',
      contact:    'Contact',
      projects:   'Projects',
    },
    hero: {
      primaryCta:   'View my work',
      secondaryCta: 'Download CV',
      availability: 'Available for graduate roles · Summer 2026',
    },
    about: {
      title: 'About.',
      body:  "I'm a final-year Applied Computer Science student at Thomas More who builds software that actually works in the real world, not just in a classroom. Three years of hands-on projects and an internship at H.Essers have taught me how to take an idea from concept to a product people use. I care about writing code that other developers can maintain, and designing experiences that make sense to the people using them.",
      body2: 'Outside of code: handball, the gym, and reading about whatever rabbit-hole technology I\'m currently obsessed with.',
      facts: [
        { label: 'Based in',   value: 'LOMMEL, BE' },
        { label: 'Experience', value: '5 YEARS'     },
        { label: 'Focus',      value: 'MOBILE · WEB · APIS' },
        { label: 'Open to',    value: 'INTERNSHIPS · JUNIOR ROLES' },
      ],
      personalDataLabel: '// PERSONAL DATA',
      languagesLabel:    '// LANGUAGES',
      interestsLabel:    '// INTERESTS',
      cvView:     'View PDF',
      cvDownload: 'Download PDF',
      langDutch:        'Dutch',   langDutchLevel:   'Native',
      langEnglish:      'English', langEnglishLevel: 'Professional',
      langFrench:       'French',  langFrenchLevel:  'Basic',
      interest1Name: '🤾 Handball',     interest1Val: 'Teamwork · Pressure · Agile mindset',
      interest2Name: '🏋️ Fitness',      interest2Val: 'Discipline · Consistency · Focus',
      interest3Name: '📖 Tech reading', interest3Val: 'Continuous learning · Curiosity',
      interest4Name: '🏛️ History',      interest4Val: 'Pattern recognition · Long-term thinking',
    },
    dataCard: {
      name:     'Name',
      role:     'Role',
      focus:    'Focus',
      status:   'Status',
      location: 'Location',
      license:  'Driving License',
    },
    skills: {
      heading: 'Stack.',
      hint:    '// hover bars for proficiency %',
      groups: [
        { title: 'Languages'         },
        { title: 'Frameworks'        },
        { title: 'Tools & Platforms' },
      ],
    },
    softskills: {
      heading: 'Soft Skills.',
      proof1: 'Ran code reviews across a 6-person team, catching edge cases before client demos.',
      proof2: 'Built and deployed the Handbal Overpelt website solo — brief to live domain, no project manager.',
      proof3: 'Guided an international exchange camp in Malta, adapting to dynamic situations daily while supporting participants and staff in a multilingual team.',
      proof4: 'Every project I build starts with the question: who uses this and what do they actually need? Applied from freelance client work to enterprise tooling at H.Essers.',
    },
    education: {
      title:   'EDUCATION',
      heading: 'Education.',
      entry1Title:  'Bachelor Applied Computer Science',
      entry1Period: 'Expected June 2026',
      entry1Org:    'Thomas More · Geel · Sep 2023 – Jun 2026',
      entry1Desc:   'Specialisation: Application development & software engineering. Focus on mobile, web and custom made applications.',
      entry2Title:  'Accountancy & Informatics',
      entry2Period: '2021 – 2023',
      entry2Org:    'WICO Campus · Lommel',
      entry2Desc:   'TSO — Combination of accounting, IT fundamentals and business administration.',
      items: [
        { period: '2023 – 2026', degree: 'Bachelor Applied Computer Science', school: 'Thomas More · Geel',    detail: 'Specialisation: Software development. Focus on mobile, web and cloud architecture.' },
        { period: '2017 – 2023', degree: 'Industrial Sciences',               school: 'Secondary · TIO',       detail: 'Mathematics, physics and the foundations that made computer science feel natural.' },
      ],
    },
    experience: {
      title:   'EXPERIENCE',
      heading: 'Experience.',
      entry1Title: 'Intern Software Developer',
      entry1Org:   'H.Essers · Genk, BE',
      entry1Desc:  'Developed a <strong>full-stack</strong> email ingestion system integrating an <strong>Outlook Add-in</strong> (Office.js) with a <strong>Java 21 / Spring Boot REST API</strong> and <strong>Apache Kafka</strong> for event-driven downstream processing. Implemented a <strong>Kafka consumer service</strong> with <strong>deduplication</strong> and <strong>retry logic</strong> handling. Validated reliability through <strong>unit/integration tests</strong> and k6 <strong>load testing</strong>.',
      entry2Title: 'Exchange Animator',
      entry2Org:   'YES camp · Malta',
      entry2Desc:  '<strong>Guiding</strong> and animating young people from Malta during an <strong>international exchange</strong> camp. <strong>Working together</strong> in an <strong>international team</strong> of supervisors and volunteers. Adapted quickly to <strong>dynamic situations</strong> while supporting both participants and staff members.',
      entry3Title: 'Service Desk Agent',
      entry3Org:   'Melexis · Tessenderlo-Ham',
      entry3Desc1: 'Provided <strong>technical support</strong> to internal staff, <strong>troubleshooting</strong> hardware, software and network issues. <strong>Collaborated</strong> with the <strong>global Service Desk team</strong> to deliver effective IT solutions.',
      entry4Title: 'Service Desk Agent',
      entry4Desc2: 'Gained <strong>hands-on experience</strong> with IT systems and company infrastructure. Built <strong>foundational knowledge</strong> of corporate IT infrastructure and day-to-day technical operations.',
      items: [
        { period: 'Sep 2025 – Present', role: 'Software Engineering Intern',  company: 'H.Essers',                        location: 'Genk, BE',    summary: 'Built an Outlook Add-in, extended the Gateway API and shipped a new Ingest API for the logistics platform.' },
        { period: '2024 – 2025',        role: 'Freelance Web Developer',      company: 'Handbal Overpelt',                location: 'Overpelt, BE',summary: "Designed, built and maintain the club's public website. Ongoing small-scope contract." },
        { period: '2024',               role: 'Student Developer',            company: 'De Beerse Bende (school client)', location: 'Thomas More', summary: 'Team member on a live client project — 6-person agile team delivering a full business application over one semester.' },
      ],
    },
    featured: {
      periodRole:    'Feb 2026 – May 2026 · Intern Software Developer',
      problemLabel:  '01 / PROBLEM',
      approachLabel: '02 / APPROACH',
      solutionLabel: '03 / SOLUTION',
      problem:  'Logistics coordinators at H.Essers spent significant time context-switching between Outlook and internal dispatch systems. Shipment data arriving by email had to be manually re-entered',
      approach: 'I designed and built an Outlook Add-in that lets users submit selected emails and their attachments to a downstream system. Behind an API gateway, I implemented an Ingest API that retrieves the full email via Microsoft Graph and publishes a structured event to a Kafka topic for async downstream processing.',
      solution: 'Coordinators can forward an email directly from Outlook without leaving the app. The backend processes it asynchronously, stores the content, and triggers the downstream workflow — fully logged and traceable end to end',
      outcomesLabel: '// OUTCOMES',
      learnedLabel:  '// LEARNED',
      outcomes: [
        'Delivered a fully working proof of concept covering the end-to-end email ingestion flow',
        'Built a custom Ingest API with deduplication and retry logic',
        'CI/CD pipeline set up for Github — ready to deploy when the organisation decides to roll out',
        'Full technical documentation written covering architecture, API contracts and deployment steps',
      ],
      learned: [
        'Shipping software inside an enterprise release process',
        'Designing APIs for other teams to actually consume',
        'Security, auth and observability in production systems',
        'How to translate vague business requests into technical specs',
      ],
      caseStudyBtn: 'Full case study →',
    },
    projects: {
      title:           'Other Work.',
      heading:         'Projects.',
      filterAll:       'All',
      filterWebApp:    'Web App',
      filterClient:    'Client',
      filterEcommerce: 'E-commerce',
      filterPersonal:  'Personal',
      items: [
        { key: 'de-beerse-bende',  category: 'web-app',    name: 'De Beerse Bende',  type: 'Web Application · Team of 6', year: '2024', stack: ['Laravel','Tailwind CSS','MySQL'],  blurb: 'Full business platform for a local client — inventory, calendar, role-based auth and reporting. I owned the calendar module, contributed to the API and ran code reviews.', link: 'https://app.debeersebende.be/', github: null },
        { key: 'handbal-overpelt', category: 'client',     name: 'Handbal Overpelt', type: 'Client Website · Solo',       year: '2024', stack: ['HTML','Tailwind CSS','JS'],        blurb: 'First independent client project — a full team website for my local handball club. Responsive, deployed and still live.', link: 'https://handbalcluboverpelt.be/', github: 'https://github.com/FreekBoes/HandbalOverpelt' },
        { key: 'zentech',          category: 'e-commerce', name: 'ZenTech',          type: 'E-commerce · Solo',           year: '2024', stack: ['Laravel','Tailwind CSS'],          blurb: 'A complete webshop built for the Web Development course — product catalog, cart, checkout and an admin panel. Top marks.', link: null, github: null },
        { key: 'first-portfolio',  category: 'personal',   name: 'First Portfolio',  type: 'Personal · Solo',             year: '2023', stack: ['Bootstrap','HTML','CSS'],          blurb: 'My first portfolio, built in my own time. Kept here to show how far the craft has come.', link: 'src/First_portfolio/index.html', github: 'https://github.com/FreekBoes/freekboes.github.io' },
      ],
    },
    contact: {
      label:          '// 07 · GET IN TOUCH',
      reachOutLabel:  '// REACH OUT',
      body: "I'm actively looking for a first role after graduation — ideally somewhere I can keep shipping real software and learning from senior engineers. If that sounds like your team, let's talk.",
    },
    modal: {
      label:       '// PROJECT DETAIL',
      assignment:  '// ASSIGNMENT',
      approach:    '// APPROACH',
      finalResult: '// FINAL RESULT',
      myInput:     '// MY INPUT',
      screenshots: '// SCREENSHOTS',
      githubBtn:   'GitHub',
      viewBtn:     'View Project ↗',
    },
    footer: 'Designed and built by Freek Boes · 2026',

    projectDetails: {
      'de-beerse-bende': {
        title: 'De Beerse Bende',
        type: 'Web Application · Team of 6',
        year: '2024',
        stack: ['Laravel', 'Tailwind CSS', 'MySQL', 'PHP'],
        link: 'https://app.debeersebende.be/',
        github: null,
        assignment: 'Build a full business platform for a real local client within one semester. The platform needed to handle inventory management, staff scheduling, role-based access control and reporting — all delivered as a working product.',
        approach: 'Working in an agile team of 6, we split the application into modules and each took ownership of a part. We held weekly sprint reviews, used Git for version control and ran code reviews before every merge to keep quality consistent.',
        finalResult: 'A fully working business platform delivered on time to a paying client. The application has been in active use since delivery, covering all the modules the client requested.',
        myInput: 'I owned the calendar module end-to-end — from database design to frontend implementation. I also contributed to the API layer and ran code reviews across the team throughout the project.',
        photos: [],
      },
      'handbal-overpelt': {
        title: 'Handbal Overpelt',
        type: 'Client Website · Solo',
        year: '2024',
        stack: ['HTML', 'Tailwind CSS', 'JavaScript'],
        link: 'https://handbalcluboverpelt.be/',
        github: 'https://github.com/FreekBoes/HandbalOverpelt',
        assignment: 'Design and build a fully responsive public website for my local handball club. The club needed a place to publish news, team info and match schedules — deployed on a live domain.',
        approach: 'I gathered requirements directly with the club board, designed the layout myself and built the site from scratch. I chose a mobile-first approach to make sure it worked well on phones, which is how most visitors access it.',
        finalResult: 'A live, responsive website deployed within two weeks of starting the project. The site is still in active use and maintained under an ongoing contract.',
        myInput: 'Sole developer — responsible for everything from the initial client conversation to deployment and ongoing maintenance.',
        photos: [],
      },
      zentech: {
        title: 'ZenTech',
        type: 'E-commerce · Solo',
        year: '2024',
        stack: ['Laravel', 'Tailwind CSS', 'MySQL'],
        link: null,
        github: null,
        assignment: 'Build a complete e-commerce platform for the Web Development course at Thomas More — including product catalogue, shopping cart, checkout flow, order management and a full admin panel.',
        approach: 'I planned the database schema first, then built the backend with Laravel following MVC principles before moving to the frontend. The admin panel was built from scratch rather than using a package, to demonstrate full understanding of the architecture.',
        finalResult: 'A fully functional webshop covering the entire shopping flow from browse to order confirmation. Received the highest grade in the class.',
        myInput: 'Sole developer on all layers — database design, backend logic, frontend implementation, testing and deployment.',
        photos: [],
      },
      'first-portfolio': {
        title: 'First Portfolio',
        type: 'Personal · Solo',
        year: '2023',
        stack: ['Bootstrap', 'HTML', 'CSS', 'JavaScript'],
        link: 'src/First_portfolio/index.html',
        github: 'https://github.com/FreekBoes/freekboes.github.io',
        assignment: 'Build a personal portfolio website to present myself professionally during the first year of my studies — entirely self-directed with no assignment or deadline.',
        approach: 'Used Bootstrap to speed up development and focused on getting something live rather than waiting for it to be perfect. Kept the scope small and shipped it.',
        finalResult: 'A live portfolio that gave me something concrete to show when applying for projects. Kept here as a benchmark to show growth.',
        myInput: 'Solo project from concept to deployment — design, development and hosting all handled independently.',
        photos: [],
      },
    },

    stage: {
      heroLabel:    '// INTERNSHIP CASE STUDY',
      heroDesc:     'A proof of concept built during my internship at H.Essers — a logistics company based in Genk, Belgium. The project automates the manual process of forwarding shipment emails from Outlook into an internal dispatch system, using an Outlook Add-in paired with an event-driven backend.',
      btnRealisatie: 'Realisatie document ↗',
      btnReflectie:  'Reflectie document ↗',
      btnPlan:       'Project plan ↗',
      metaCompany:  'COMPANY',
      metaRole:     'ROLE',
      metaDuration: 'DURATION',
      metaScope:    'SCOPE',
      aboutLabel:   '// ABOUT H.ESSERS',
      aboutText:    'H.Essers is an international logistics and transport company headquartered in Genk, Belgium. With operations across Europe and beyond, they handle complex supply chains for sectors including healthcare, chemicals and general cargo. The company employs thousands of logistics coordinators who manage daily shipment operations — many of which still rely heavily on email workflows.',
      problemLabel:  '01 / PROBLEM',
      problemText:   'Logistics coordinators at H.Essers received shipment data by email and had to manually re-enter it into internal dispatch systems. This process was slow, error-prone and impossible to audit at scale.',
      approachLabel: '02 / APPROACH',
      approachText:  'I designed and built an Outlook Add-in that lets users submit selected emails and attachments directly to a downstream system. Behind an API gateway (Gravitee), a custom Ingest API retrieves the full email via Microsoft Graph and publishes a structured event to a Kafka topic for async downstream processing.',
      solutionLabel: '03 / SOLUTION',
      solutionText:  'Coordinators can forward an email directly from Outlook without leaving the app. The backend processes it asynchronously, stores the content, and triggers the downstream workflow — fully logged and traceable end to end.',
      archLabel:   '// TECHNICAL ARCHITECTURE',
      archHeading: 'Architecture.',
      arch1Title: 'Outlook Add-in (Frontend)', arch1Badge: 'Office.js · JavaScript',
      arch1Desc:  'Built with Office.js, the add-in renders a task pane inside Outlook. When a user selects an email and clicks submit, the add-in reads the email metadata and passes it to the API gateway. Authentication is handled via OAuth2 with Microsoft identity platform.',
      arch2Title: 'API Gateway',              arch2Badge: 'Gravitee · REST',
      arch2Desc:  'All traffic flows through Gravitee as the API gateway. It handles routing, rate limiting and security policies. The gateway forwards validated requests to the Ingest API running behind it.',
      arch3Title: 'Ingest API (Backend)',     arch3Badge: 'Java 21 · Spring Boot',
      arch3Desc:  'The core backend service. It receives the submission from the gateway, fetches the full email and attachments via the Microsoft Graph API using an OBO (On-Behalf-Of) OAuth2 flow, then publishes a structured event to a Kafka topic. Custom handling includes deduplication logic and retry mechanisms.',
      arch4Title: 'Event Streaming',          arch4Badge: 'Apache Kafka',
      arch4Desc:  'Events are published to a Kafka topic for async downstream processing. A Kafka consumer service processes each event, with deduplication to prevent duplicate submissions and full audit logging for traceability.',
      arch5Title: 'CI/CD Pipeline',           arch5Badge: 'Azure · GitHub Actions',
      arch5Desc:  'A full CI/CD pipeline was set up for GitHub Actions — including build, test and deployment stages. The pipeline is ready to deploy the full system when the organisation decides to move from proof of concept to production.',
      outcomesLabel: '// OUTCOMES',
      outcomes: [
        'Delivered a fully working proof of concept covering the end-to-end email ingestion flow',
        'Built a custom Ingest API with deduplication and retry logic',
        'CI/CD pipeline set up for Github — ready to deploy when the organisation decides to roll out',
        'Full technical documentation written covering architecture, API contracts and deployment steps',
      ],
      learnedLabel: '// LEARNED',
      learned: [
        'Shipping software inside an enterprise release process',
        'Designing APIs for other teams to actually consume',
        'Security, auth and observability in production systems',
        'How to translate vague business requests into technical specs',
      ],
      photosLabel:  '// PHOTOS',
      photosHeading: 'Photos.',
      docsLabel:    '// DOCUMENTS',
      docsHeading:  'Documents.',
      doc1Title: 'Realisatie Document',
      doc1Desc:  'Technical realisation document describing the implementation, architecture decisions and deliverables of the internship project.',
      doc1Btn:   'Open PDF ↗',
      doc2Title: 'Reflectie Document',
      doc2Desc:  'Personal reflection on the internship experience — what went well, what I would do differently, and how the project shaped my growth as a developer.',
      doc2Btn:   'Open PDF ↗',
      doc3Title: 'Project Plan',
      doc3Desc:  'The initial project plan submitted at the start of the internship — scope, objectives, timeline and technical approach.',
      doc3Btn:   'Open PDF ↗',
      footer:   'Freek Boes · Internship H.Essers · 2026',
      backLink: '← Back to portfolio',
    },

  },


  nl: {
    status:  'Laatste jaar · Thomas More',
    role:    'Toegepaste Informatica',
    tagline: 'Software developer gespecialiseerd in mobiele en webapplicaties die echte bedrijfsproblemen oplossen.',
    nav: {
      about:      'Over',
      skills:     'Stack',
      work:       'Stage',
      experience: 'Ervaring',
      education:  'Opleiding',
      resume:     'CV',
      contact:    'Contact',
      projects:   'Projecten',
    },
    hero: {
      primaryCta:   'Bekijk mijn werk',
      secondaryCta: 'Download CV',
      availability: 'Beschikbaar voor starterfuncties · Zomer 2026',
    },
    about: {
      title: 'Over mij.',
      body:  'Ik ben een laatstejaarsstudent Toegepaste Informatica aan Thomas More. In drie jaar ben ik gegroeid van mijn eerste regel HTML naar het opleveren van een volledig werkende proof of concept bij H.Essers. Ik zorg ervoor dat mijn code onderhoudbaar is voor andere developers en dat de gebruikerservaring logisch aanvoelt voor de mensen die het gebruiken.',
      body2: 'Naast code: handbal, de gym en verdiepen in welke tech-rabbit-hole me nu boeit.',
      facts: [
        { label: 'Locatie',   value: 'LOMMEL, BE' },
        { label: 'Ervaring',  value: '5 JAAR'      },
        { label: 'Focus',     value: 'MOBILE · WEB · APIS' },
        { label: 'Open voor', value: 'STAGES · STARTER' },
      ],
      personalDataLabel: '// PERSOONLIJKE GEGEVENS',
      languagesLabel:    '// TALEN',
      interestsLabel:    '// INTERESSES',
      cvView:     'PDF bekijken',
      cvDownload: 'PDF downloaden',
      langDutch:        'Nederlands', langDutchLevel:   'Moedertaal',
      langEnglish:      'Engels',     langEnglishLevel: 'Professioneel',
      langFrench:       'Frans',      langFrenchLevel:  'Basis',
      interest1Name: '🤾 Handbal',       interest1Val: 'Teamwork · Druk · Agile mindset',
      interest2Name: '🏋️ Fitness',       interest2Val: 'Discipline · Consistentie · Focus',
      interest3Name: '📖 Tech lezen',    interest3Val: 'Continu leren · Nieuwsgierigheid',
      interest4Name: '🏛️ Geschiedenis',  interest4Val: 'Patroonherkenning · Langetermijndenken',
    },
    dataCard: {
      name:     'Naam',
      role:     'Functie',
      focus:    'Focus',
      status:   'Status',
      location: 'Locatie',
      license:  'Rijbewijs',
    },
    skills: {
      heading: 'Stack.',
      hint:    '// hover over balken voor vaardigheid %',
      groups: [
        { title: 'Talen'              },
        { title: 'Frameworks'         },
        { title: 'Tools & Platformen' },
      ],
    },
    softskills: {
      heading: 'Soft Skills.',
      proof1: 'Voerde code reviews uit binnen een team van 6 en ontdekte edge cases vóór de klantdemo\'s.',
      proof2: 'De website van Handbal Overpelt solo gebouwd en uitgerold — van briefing tot live domein, zonder projectmanager.',
      proof3: 'Leidde een internationaal uitwisselingskamp op Malta en paste me dagelijks aan dynamische situaties aan terwijl ik deelnemers en medewerkers ondersteunde in een meertalig team.',
      proof4: 'Elk project begint met de vraag: wie gebruikt dit en wat hebben ze echt nodig? Toegepast van freelance klantwerk tot enterprise tooling bij H.Essers.',
    },
    education: {
      title:   'OPLEIDING',
      heading: 'Opleiding.',
      entry1Title:  'Bachelor Toegepaste Informatica',
      entry1Period: 'Verwacht juni 2026',
      entry1Org:    'Thomas More · Geel · Sep 2023 – Jun 2026',
      entry1Desc:   'Afstudeerrichting: Applicatieontwikkeling & software engineering. Focus op mobiele, web- en maatwerkapplicaties.',
      entry2Title:  'Boekhouden-Informatica',
      entry2Period: '2021 – 2023',
      entry2Org:    'WICO Campus · Lommel',
      entry2Desc:   'TSO — Combinatie van boekhouding, IT-fundamenten en bedrijfsadministratie.',
      items: [
        { period: '2023 – 2026', degree: 'Bachelor Toegepaste Informatica', school: 'Thomas More · Geel', detail: 'Afstudeerrichting: Software development. Focus op mobile, web en cloud-architectuur.' },
        { period: '2017 – 2023', degree: 'Industriële Wetenschappen',       school: 'Secundair · TIO',    detail: 'Wiskunde, fysica en de basis die informatica natuurlijk deed aanvoelen.' },
      ],
    },
    experience: {
      title:   'ERVARING',
      heading: 'Ervaring.',
      entry1Title: 'Stagiair Softwareontwikkelaar',
      entry1Org:   'H.Essers · Genk, BE',
      entry1Desc:  'Ontwikkelde een <strong>full-stack</strong> e-mailingestiesysteem dat een <strong>Outlook Add-in</strong> (Office.js) integreert met een <strong>Java 21 / Spring Boot REST API</strong> en <strong>Apache Kafka</strong> voor event-driven downstream-verwerking. Implementeerde een <strong>Kafka-consumerservice</strong> met <strong>deduplicatie</strong> en <strong>retry-logica</strong>. Gevalideerde betrouwbaarheid via <strong>unit/integratietests</strong> en k6 <strong>belastingstests</strong>.',
      entry2Title: 'Exchange Animator',
      entry2Org:   'YES camp · Malta',
      entry2Desc:  '<strong>Begeleiden</strong> en animeren van jongeren uit Malta tijdens een <strong>internationaal uitwisselingskamp</strong>. <strong>Samenwerken</strong> in een <strong>internationaal team</strong> van begeleiders en vrijwilligers. Snel aangepast aan <strong>dynamische situaties</strong> terwijl zowel deelnemers als medewerkers werden ondersteund.',
      entry3Title: 'Service Desk Medewerker',
      entry3Org:   'Melexis · Tessenderlo-Ham',
      entry3Desc1: 'Verleende <strong>technische ondersteuning</strong> aan interne medewerkers, <strong>probleemoplossing</strong> voor hardware-, software- en netwerkproblemen. <strong>Samengewerkt</strong> met het <strong>globale Service Desk-team</strong> om effectieve IT-oplossingen te leveren.',
      entry4Title: 'Service Desk Medewerker',
      entry4Desc2: 'Deed <strong>praktijkervaring</strong> op met IT-systemen en bedrijfsinfrastructuur. Bouwde <strong>fundamentele kennis</strong> op van bedrijfs-IT-infrastructuur en dagelijkse technische operaties.',
      items: [
        { period: 'Sep 2025 – Heden', role: 'Software Engineering Stagiair', company: 'H.Essers',                           location: 'Genk, BE',      summary: 'Outlook Add-in gebouwd, Gateway API uitgebreid en een nieuwe Ingest API uitgerold voor het logistieke platform.' },
        { period: '2024 – 2025',      role: 'Freelance Web Developer',       company: 'Handbal Overpelt',                   location: 'Overpelt, BE',  summary: 'De publieke website van de club ontworpen, gebouwd en nog steeds onderhouden.' },
        { period: '2024',             role: 'Student Developer',             company: 'De Beerse Bende (schoolklant)',      location: 'Thomas More',   summary: 'Teamlid op een live klantproject — agile team van 6 dat één semester lang een volledig business-systeem afleverde.' },
      ],
    },
    featured: {
      periodRole:    'Feb 2026 – Mei 2026 · Stagiair Softwareontwikkelaar',
      problemLabel:  '01 / PROBLEEM',
      approachLabel: '02 / AANPAK',
      solutionLabel: '03 / OPLOSSING',
      problem:  'Logistieke coördinatoren bij H.Essers verloren tijd met schakelen tussen Outlook en interne dispatch-systemen. Zendingdata in e-mails moest manueel overgetypt worden in de gateway — traag, foutgevoelig en moeilijk te auditen.',
      approach: 'Ik heb een Outlook Add-in ontworpen en gebouwd die inkomende zending-e-mails parset en gestructureerde acties in-context toont. Aan de backend heb ik de bestaande Gateway API uitgebreid en een nieuwe Ingest API geïmplementeerd zodat data proper van e-mail naar het dispatch-platform stroomt.',
      solution: 'De add-in maakt van een manuele taak van 4 minuten een bevestiging in twee kliks, en de Ingest API geeft operations één bron van waarheid voor inkomende zendingen — met validatie, retry en audit trail.',
      outcomesLabel: '// RESULTATEN',
      learnedLabel:  '// GELEERD',
outcomes: [
  'Een volledig werkende proof of concept geleverd die de end-to-end e-mailingestie-flow dekt',
  'Een aangepaste Ingest API gebouwd met deduplicatie en retry-logica',
  'CI/CD-pipeline opgezet — klaar voor deployment wanneer de organisatie besluit uit te rollen',
  'Volledige technische documentatie geschreven over architectuur, API-contracten en deployment-stappen',
],
      learned: [
        'Software leveren binnen een enterprise release-proces',
        'APIs ontwerpen die andere teams effectief gebruiken',
        'Security, auth en observability in productie',
        'Vage business-vragen vertalen naar technische specs',
      ],
      caseStudyBtn: 'Volledige case study →',
    },
    projects: {
      title:           'Ander Werk.',
      heading:         'Projecten.',
      filterAll:       'Alle',
      filterWebApp:    'Web App',
      filterClient:    'Klant',
      filterEcommerce: 'E-commerce',
      filterPersonal:  'Persoonlijk',
      items: [
        { key: 'de-beerse-bende',  category: 'web-app',    name: 'De Beerse Bende',  type: 'Web Applicatie · Team van 6', year: '2024', stack: ['Laravel','Tailwind CSS','MySQL'],  blurb: 'Volledig business-platform voor een lokale klant — inventaris, kalender, role-based auth en rapportering. Ik was verantwoordelijk voor de kalender, API-bijdragen en code reviews.', link: 'https://app.debeersebende.be/', github: null },
        { key: 'handbal-overpelt', category: 'client',     name: 'Handbal Overpelt', type: 'Klant Website · Solo',        year: '2024', stack: ['HTML','Tailwind CSS','JS'],        blurb: 'Mijn eerste onafhankelijk klantproject — een volledige teamwebsite voor mijn lokale handbalclub. Responsive, live en nog steeds in gebruik.', link: 'https://handbalcluboverpelt.be/', github: 'https://github.com/FreekBoes/HandbalOverpelt' },
        { key: 'zentech',          category: 'e-commerce', name: 'ZenTech',          type: 'E-commerce · Solo',           year: '2024', stack: ['Laravel','Tailwind CSS'],          blurb: 'Volledige webshop voor de cursus Web Development — productcatalogus, cart, checkout en admin-panel. Hoogste cijfer.', link: null, github: null },
        { key: 'first-portfolio',  category: 'personal',   name: 'First Portfolio',  type: 'Persoonlijk · Solo',          year: '2023', stack: ['Bootstrap','HTML','CSS'],          blurb: 'Mijn eerste portfolio, gebouwd in eigen tijd. Bewaard om te tonen hoever het vakmanschap is gekomen.', link: 'src/First_portfolio/index.html', github: 'https://github.com/FreekBoes/freekboes.github.io' },
      ],
    },
    contact: {
      label:         '// 07 · CONTACTEER MIJ',
      reachOutLabel: '// BEREIK MIJ',
      body: 'Ik ben actief op zoek naar een eerste job na mijn studie — liefst ergens waar ik echte software kan blijven bouwen en leren van senior engineers. Klinkt dat als jouw team? Laten we praten.',
    },
    modal: {
      label:       '// PROJECT DETAIL',
      assignment:  '// OPDRACHT',
      approach:    '// AANPAK',
      finalResult: '// EINDRESULTAAT',
      myInput:     '// MIJN BIJDRAGE',
      screenshots: '// SCREENSHOTS',
      githubBtn:   'GitHub',
      viewBtn:     'Project bekijken ↗',
    },
    footer: 'Ontworpen en gebouwd door Freek Boes · 2026',

    projectDetails: {
      'de-beerse-bende': {
        title: 'De Beerse Bende',
        type: 'Web Applicatie · Team van 6',
        year: '2024',
        stack: ['Laravel', 'Tailwind CSS', 'MySQL', 'PHP'],
        link: 'https://app.debeersebende.be/',
        github: null,
        assignment: 'Bouw een volledig business platform voor een echte lokale klant binnen één semester. Het platform moest inventarisbeheer, personeelsplanning, rolgebaseerde toegangscontrole en rapportage afhandelen — allemaal als werkend product opgeleverd.',
        approach: 'Werkend in een agile team van 6 verdeelden we de applicatie in modules en nam iedereen eigenaarschap over een deel. We hielden wekelijkse sprint reviews, gebruikten Git voor versiebeheer en deden code reviews voor elke merge om de kwaliteit consistent te houden.',
        finalResult: 'Een volledig werkend business platform op tijd geleverd aan een betalende klant. De applicatie is actief in gebruik sinds de oplevering en dekt alle modules die de klant gevraagd had.',
        myInput: 'Ik was verantwoordelijk voor de kalendermodule van begin tot einde — van database-ontwerp tot frontend-implementatie. Ik droeg ook bij aan de API-laag en voerde code reviews uit over het hele team.',
        photos: [],
      },
      'handbal-overpelt': {
        title: 'Handbal Overpelt',
        type: 'Klant Website · Solo',
        year: '2024',
        stack: ['HTML', 'Tailwind CSS', 'JavaScript'],
        link: 'https://handbalcluboverpelt.be/',
        github: 'https://github.com/FreekBoes/HandbalOverpelt',
        assignment: 'Ontwerp en bouw een volledig responsive publieke website voor mijn lokale handbalclub. De club had een plek nodig voor nieuws, teaminfo en wedstrijdschema\'s — uitgerold op een live domein.',
        approach: 'Ik verzamelde requirements rechtstreeks bij het clubbestuur, ontwierp de lay-out zelf en bouwde de site van nul. Ik koos een mobile-first aanpak zodat het goed werkte op telefoons, wat de meeste bezoekers gebruiken.',
        finalResult: 'Een live, responsive website uitgerold binnen twee weken na de start van het project. De site is nog steeds actief in gebruik en wordt onderhouden via een doorlopend contract.',
        myInput: 'Enige ontwikkelaar — verantwoordelijk voor alles van het eerste klantgesprek tot deployment en doorlopend onderhoud.',
        photos: [],
      },
      zentech: {
        title: 'ZenTech',
        type: 'E-commerce · Solo',
        year: '2024',
        stack: ['Laravel', 'Tailwind CSS', 'MySQL'],
        link: null,
        github: null,
        assignment: 'Bouw een volledig e-commerce platform voor de cursus Web Development aan Thomas More — inclusief productcatalogus, winkelwagen, checkout-flow, orderbeheer en een volledig adminpanel.',
        approach: 'Ik plande het databaseschema eerst, bouwde daarna de backend met Laravel volgens MVC-principes en ging dan naar de frontend. Het adminpanel werd zelf gebouwd in plaats van een pakket te gebruiken, om het volledige begrip van de architectuur te tonen.',
        finalResult: 'Een volledig functionele webshop die de volledige shoppingflow van browsen tot orderbevestiging dekt. Hoogste cijfer van de klas ontvangen.',
        myInput: 'Enige ontwikkelaar op alle lagen — database-ontwerp, backend-logica, frontend-implementatie, testen en deployment.',
        photos: [],
      },
      'first-portfolio': {
        title: 'First Portfolio',
        type: 'Persoonlijk · Solo',
        year: '2023',
        stack: ['Bootstrap', 'HTML', 'CSS', 'JavaScript'],
        link: 'src/First_portfolio/index.html',
        github: 'https://github.com/FreekBoes/freekboes.github.io',
        assignment: 'Bouw een persoonlijke portfoliowebsite om mezelf professioneel te presenteren tijdens het eerste jaar van mijn studie — volledig zelfsturend zonder opdracht of deadline.',
        approach: 'Gebruikte Bootstrap om de ontwikkeling te versnellen en focuste op iets live krijgen in plaats van wachten op perfectie. Hield de scope klein en leverde het op.',
        finalResult: 'Een live portfolio dat me iets concreets gaf om te tonen bij het solliciteren naar projecten. Bewaard hier als referentiepunt om groei te tonen.',
        myInput: 'Solo project van concept tot deployment — ontwerp, ontwikkeling en hosting allemaal zelf afgehandeld.',
        photos: [],
      },
    },

    stage: {
      heroLabel:    '// STAGE CASE STUDY',
      heroDesc:     'Een proof of concept gebouwd tijdens mijn stage bij H.Essers — een logistiek bedrijf gevestigd in Genk, België. Het project automatiseert het handmatige proces van het doorsturen van zending-e-mails vanuit Outlook naar een intern dispatch-systeem, met behulp van een Outlook Add-in gekoppeld aan een event-driven backend.',
      btnRealisatie: 'Realisatiedocument ↗',
      btnReflectie:  'Reflectiedocument ↗',
      btnPlan:       'Projectplan ↗',
      metaCompany:  'BEDRIJF',
      metaRole:     'ROL',
      metaDuration: 'PERIODE',
      metaScope:    'OMVANG',
      aboutLabel:   '// OVER H.ESSERS',
      aboutText:    'H.Essers is een internationaal logistiek en transportbedrijf met hoofdkantoor in Genk, België. Met activiteiten doorheen Europa en daarbuiten beheren ze complexe toeleveringsketens voor sectoren zoals gezondheidszorg, chemicaliën en algemene lading. Het bedrijf stelt duizenden logistieke coördinatoren in dienst die dagelijkse zendingsoperaties beheren — waarvan er veel nog sterk afhankelijk zijn van e-mailworkflows.',
      problemLabel:  '01 / PROBLEEM',
      problemText:   'Logistieke coördinatoren bij H.Essers ontvingen zendingsgegevens per e-mail en moesten deze handmatig opnieuw invoeren in interne dispatch-systemen. Dit proces was traag, foutgevoelig en onmogelijk op schaal te auditen.',
      approachLabel: '02 / AANPAK',
      approachText:  'Ik ontwierp en bouwde een Outlook Add-in waarmee gebruikers geselecteerde e-mails en bijlagen rechtstreeks naar een downstream systeem kunnen doorsturen. Achter een API-gateway (Gravitee) haalt een aangepaste Ingest API de volledige e-mail op via Microsoft Graph en publiceert een gestructureerd event naar een Kafka-topic voor asynchrone downstream-verwerking.',
      solutionLabel: '03 / OPLOSSING',
      solutionText:  'Coördinatoren kunnen een e-mail rechtstreeks vanuit Outlook doorsturen zonder de app te verlaten. De backend verwerkt dit asynchroon, slaat de inhoud op en triggert de downstream-workflow — volledig gelogd en traceerbaar van begin tot eind.',
      archLabel:   '// TECHNISCHE ARCHITECTUUR',
      archHeading: 'Architectuur.',
      arch1Title: 'Outlook Add-in (Frontend)', arch1Badge: 'Office.js · JavaScript',
      arch1Desc:  'Gebouwd met Office.js rendert de add-in een taakvenster binnen Outlook. Wanneer een gebruiker een e-mail selecteert en op verzenden klikt, leest de add-in de e-mailmetadata en geeft deze door aan de API-gateway. Authenticatie wordt afgehandeld via OAuth2 met het Microsoft identiteitsplatform.',
      arch2Title: 'API Gateway',              arch2Badge: 'Gravitee · REST',
      arch2Desc:  'Al het verkeer loopt via Gravitee als API-gateway. Het verwerkt routering, snelheidsbeperking en beveiligingsbeleid. De gateway stuurt gevalideerde verzoeken door naar de Ingest API die erachter draait.',
      arch3Title: 'Ingest API (Backend)',     arch3Badge: 'Java 21 · Spring Boot',
      arch3Desc:  'De centrale backend-service. Het ontvangt de inzending van de gateway, haalt de volledige e-mail en bijlagen op via de Microsoft Graph API met een OBO OAuth2-flow, en publiceert een gestructureerd event naar een Kafka-topic. Aangepaste verwerking omvat deduplicatielogica en retry-mechanismen.',
      arch4Title: 'Event Streaming',          arch4Badge: 'Apache Kafka',
      arch4Desc:  'Events worden gepubliceerd naar een Kafka-topic voor asynchrone downstream-verwerking. Een Kafka-consumerservice verwerkt elk event, met deduplicatie om dubbele inzendingen te voorkomen en volledige auditregistratie voor traceerbaarheid.',
      arch5Title: 'CI/CD Pipeline',           arch5Badge: 'Azure · GitHub Actions',
      arch5Desc:  'Een volledige CI/CD-pipeline werd opgezet voor GitHub Actions — inclusief build-, test- en deployment-fasen. De pipeline is klaar om het volledige systeem te deployen wanneer de organisatie besluit van proof of concept naar productie te gaan.',
      outcomesLabel: '// RESULTATEN',
      outcomes: [
        'Een volledig werkende proof of concept geleverd die de end-to-end e-mailingestie-flow dekt',
        'Een aangepaste Ingest API gebouwd met deduplicatie en retry-logica ',
        'CI/CD-pipeline opgezet op Azure — klaar voor deployment wanneer de organisatie besluit uit te rollen',
        'Volledige technische documentatie geschreven over architectuur, API-contracten en deployment-stappen',
      ],
      learnedLabel: '// GELEERD',
      learned: [
        'Software leveren binnen een enterprise release-proces',
        'APIs ontwerpen die andere teams effectief kunnen gebruiken',
        'Beveiliging, auth en observability in productiesystemen',
        'Vage bedrijfsvragen vertalen naar technische specificaties',
      ],
      photosLabel:   "// FOTO'S",
      photosHeading: "Foto's.",
      docsLabel:    '// DOCUMENTEN',
      docsHeading:  'Documenten.',
      doc1Title: 'Realisatiedocument',
      doc1Desc:  'Technisch realisatiedocument dat de implementatie, architectuurbeslissingen en deliverables van het stageproject beschrijft.',
      doc1Btn:   'Open PDF ↗',
      doc2Title: 'Reflectiedocument',
      doc2Desc:  'Persoonlijke reflectie op de stage-ervaring — wat goed ging, wat ik anders zou doen en hoe het project mijn groei als developer heeft vormgegeven.',
      doc2Btn:   'Open PDF ↗',
      doc3Title: 'Projectplan',
      doc3Desc:  'Het initiële projectplan ingediend aan het begin van de stage — scope, doelstellingen, tijdlijn en technische aanpak.',
      doc3Btn:   'Open PDF ↗',
      footer:   'Freek Boes · Stage H.Essers · 2026',
      backLink: '← Terug naar portfolio',
    },

  },

};